-- =========================================================
-- SIA PHOTObooth
-- DATABASE: Supabase PostgreSQL
-- =========================================================

-- =========================================================
-- 1. HAPUS TABEL LAMA
-- =========================================================

drop table if exists public.penerimaan_kas cascade;
drop table if exists public.penyewaan cascade;
drop table if exists public.paket cascade;
drop table if exists public.pelanggan cascade;


-- =========================================================
-- 2. TABEL PELANGGAN
-- =========================================================

create table public.pelanggan (
    id_pelanggan bigint generated by default as identity primary key,
    nama_pelanggan varchar(100) not null,
    no_hp varchar(20) not null,
    email varchar(120) not null,
    alamat text,
    created_at timestamptz not null default now()
);


-- =========================================================
-- 3. TABEL PAKET
-- =========================================================

create table public.paket (
    id_paket bigint generated by default as identity primary key,
    nama_paket varchar(100) not null unique,
    deskripsi text,
    durasi_menit integer not null
        check (durasi_menit between 15 and 20),
    harga numeric(12,2) not null
        check (harga between 35000 and 55000),
    status_aktif boolean not null default true,
    created_at timestamptz not null default now()
);


-- =========================================================
-- 4. TABEL PENYEWAAN
-- =========================================================

create table public.penyewaan (
    id_penyewaan bigint generated by default as identity primary key,

    kode_booking varchar(30) not null unique,

    id_pelanggan bigint not null
        references public.pelanggan(id_pelanggan)
        on update cascade
        on delete restrict,

    id_paket bigint not null
        references public.paket(id_paket)
        on update cascade
        on delete restrict,

    tanggal_reservasi date not null,

    jam_reservasi time not null,

    outlet varchar(100) not null,

    total_harga numeric(12,2) not null
        check (total_harga >= 0),

    status_booking varchar(20) not null default 'BOOKED'
        check (status_booking in ('BOOKED', 'CANCELLED')),

    catatan text,

    created_at timestamptz not null default now()
);


-- =========================================================
-- 5. TABEL PENERIMAAN KAS
-- =========================================================

create table public.penerimaan_kas (
    id_penerimaan bigint generated by default as identity primary key,

    no_bukti varchar(30) not null unique,

    id_penyewaan bigint not null unique
        references public.penyewaan(id_penyewaan)
        on update cascade
        on delete cascade,

    tanggal_bayar timestamptz not null default now(),

    metode_pembayaran varchar(20) not null
        check (metode_pembayaran in ('QRIS', 'M-BANKING')),

    jumlah_diterima numeric(12,2) not null
        check (jumlah_diterima > 0),

    keterangan text
);


-- =========================================================
-- 6. INDEX
-- =========================================================

create index idx_penyewaan_tanggal
on public.penyewaan(tanggal_reservasi);

create index idx_penyewaan_outlet
on public.penyewaan(outlet);

create index idx_penyewaan_pelanggan
on public.penyewaan(id_pelanggan);

create index idx_penyewaan_paket
on public.penyewaan(id_paket);

create index idx_penerimaan_tanggal
on public.penerimaan_kas(tanggal_bayar);


-- =========================================================
-- 7. CEGAH BOOKING DENGAN TANGGAL + JAM + OUTLET
--    YANG SAMA PERSIS
-- =========================================================

create unique index uq_penyewaan_same_start
on public.penyewaan(
    tanggal_reservasi,
    jam_reservasi,
    outlet
)
where status_booking = 'BOOKED';


-- =========================================================
-- 8. DATA MASTER PAKET
-- =========================================================

insert into public.paket
(
    nama_paket,
    deskripsi,
    durasi_menit,
    harga,
    status_aktif
)
values
(
    'Mini Snap',
    'Paket photobooth singkat untuk foto santai.',
    15,
    35000,
    true
),
(
    'Classic Booth',
    'Paket photobooth dengan durasi yang lebih fleksibel.',
    20,
    45000,
    true
),
(
    'Premium Booth',
    'Paket photobooth dengan durasi maksimal.',
    20,
    55000,
    true
);


-- =========================================================
-- 9. ROW LEVEL SECURITY
-- =========================================================

alter table public.pelanggan enable row level security;
alter table public.paket enable row level security;
alter table public.penyewaan enable row level security;
alter table public.penerimaan_kas enable row level security;


-- =========================================================
-- 10. POLICY PELANGGAN
-- =========================================================

create policy "anon_select_pelanggan"
on public.pelanggan
for select
to anon
using (true);

create policy "anon_insert_pelanggan"
on public.pelanggan
for insert
to anon
with check (true);

create policy "anon_update_pelanggan"
on public.pelanggan
for update
to anon
using (true)
with check (true);

create policy "anon_delete_pelanggan"
on public.pelanggan
for delete
to anon
using (true);


-- =========================================================
-- 11. POLICY PAKET
-- =========================================================

create policy "anon_select_paket"
on public.paket
for select
to anon
using (true);

create policy "anon_insert_paket"
on public.paket
for insert
to anon
with check (true);

create policy "anon_update_paket"
on public.paket
for update
to anon
using (true)
with check (true);

create policy "anon_delete_paket"
on public.paket
for delete
to anon
using (true);


-- =========================================================
-- 12. POLICY PENYEWAAN
-- =========================================================

create policy "anon_select_penyewaan"
on public.penyewaan
for select
to anon
using (true);

create policy "anon_insert_penyewaan"
on public.penyewaan
for insert
to anon
with check (true);

create policy "anon_update_penyewaan"
on public.penyewaan
for update
to anon
using (true)
with check (true);

create policy "anon_delete_penyewaan"
on public.penyewaan
for delete
to anon
using (true);


-- =========================================================
-- 13. POLICY PENERIMAAN KAS
-- =========================================================

create policy "anon_select_penerimaan_kas"
on public.penerimaan_kas
for select
to anon
using (true);

create policy "anon_insert_penerimaan_kas"
on public.penerimaan_kas
for insert
to anon
with check (true);

create policy "anon_update_penerimaan_kas"
on public.penerimaan_kas
for update
to anon
using (true)
with check (true);

create policy "anon_delete_penerimaan_kas"
on public.penerimaan_kas
for delete
to anon
using (true);


-- =========================================================
-- 14. GRANT ACCESS UNTUK ANON
-- =========================================================

grant usage on schema public to anon;

grant select, insert, update, delete
on public.pelanggan
to anon;

grant select, insert, update, delete
on public.paket
to anon;

grant select, insert, update, delete
on public.penyewaan
to anon;

grant select, insert, update, delete
on public.penerimaan_kas
to anon;


-- =========================================================
-- 15. AKSES SEQUENCE / IDENTITY
-- =========================================================

grant usage, select
on all sequences in schema public
to anon;


-- =========================================================
-- SELESAI
-- =========================================================
